### ISSUE TITLE
geo_locations are naïve and not CLDF

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#149] opened 2017-06-06 14:26 UTC
User-supplied geographic locations, passed to `languages`→`location_data` is
 - [x] in a surprising place (I expected `geography`→`data`)
 - [x] parsed by a very naïve CSV-parser (ignore first line, and assume all further lines are `iso, lat, long`)
   - [x] ISO may not be the best variable name there.
 - [ ] not compatible with the [CLDF language metadata specification](https://github.com/glottobank/cldf/tree/master/components/languages)
 - [ ] not a thing that disables glottolog import
    - Actually, this makes it difficult to work with, because beastling will assume that it can find my lects in Glottolog, when they are not in there.

**Comment by lmaurits** [comment] 2017-06-07 00:48
I fully endorse most of these as bugs, but I'm not sure including `location_data` should disable glottolog import, as you can override Glottolog's locations but still make sure of the family classifications and/or the macroregions.

**Comment by Anaphory** [comment] 2017-06-07 08:15
Sure! That's misleading phrasing on my part. I did not mean it should entirely disable it. But some slightly more clever logic about when to *en*able it depending on geography will be useful.

**Comment by lmaurits** [comment] 2017-09-13 11:11
@xrotwang I presume pycldf will make pulling in locations specified as CLDF metadata relatively painless?

**Comment by lmaurits** [comment] 2017-09-13 11:15
As for making the "house format" a bit less pokey, I guess it would be easy to use Python's `csv` module to let people use commas or tabs and to properly parse fieldnames.  We could accept (case insensitively) `lattitude` or `lat` and `longitude` or `long` for the data columns, and perhaps `iso`, `glotto`, or `language_ID` for the language identifiers (this makes things consistent with our house format for data files).

**Comment by xrotwang** [comment] 2017-09-13 11:17
Yes, CLDF is pretty explicit when it comes to coordinates:
https://github.com/glottobank/cldf/blob/992c6dcabc97dfee3c9a9b6a84ee1cb02617306b/components/languages/LanguageTable-metadata.json#L16-L31

And `pycldf` will make this data available painlessly.

**Comment by lmaurits** [comment] 2017-09-13 11:22
Alright, I'll start reading up on pycldf.  Looks like nothing in `glottobank:cldf/examples` currently has geographic metadata?

**Comment by xrotwang** [comment] 2017-09-13 11:35
The examples haven't been updated to reflect 1.0, sorry. We should have some examples in lexibank, though.

**Comment by lmaurits** [comment] 2017-09-13 11:43
No worries!

**Comment by lmaurits** [comment] 2017-09-18 06:50
The specified file is now parsed using the same UnicodeDictReader code we use for reading linguistic data.  Permitted column names are as I suggested above.

Still no handling of CLDF metadata files.

**Comment by lmaurits** [comment] 2017-09-27 11:14
Looking at the checklist in @Anaphory's first post opening this issue, aside from the big CLDF job there is only one point left, about disabling Glottolog import.  Is this still a big problem?  It's possible to override any location in Glottolog now, I guess the only remaining issue is that if you are using non-Glottocode language names and providing your own language data, BEASTling is wasting a little bit of time parsing Glottolog's location data for nothing.  This _may_ be fixable (given a list of language identifiers, it's not too hard to recognise if they are all ISO or Glottocodes, and disable reading Glottolog if not)...

**Comment by xrotwang** [comment] 2017-09-27 11:38
Hey, we are about to run BEAST, so wasting a couple of CPU cycles to parse CSV seems absolutely negligible to me :)

**Comment by lmaurits** [comment] 2017-09-27 11:46
Very true!

That said, BEASTling feels a bit sluggish at the command line these days on analyses where we do parse Glottolog.  But this is probably BEASTling doing something inefficiently with the Glottolog data after parsing it which accounts for most of this.  I should probably profile it one day.

**Comment by xrotwang** [comment] 2017-09-27 12:05
Maybe throw in some logging or a [progress bar](https://pypi.python.org/pypi/tqdm) to keep the user entertained ...

**Comment by xrotwang** [comment] 2017-09-27 12:06
That seemed to make @LinguList happier with sluggish lexibank :)

**Comment by lmaurits** [comment] 2017-09-27 12:10
I must confess to oggling the tqdm progress bars while sitting next to @LinguList on Seili, and asking which library he was using!  Looks a lot nicer than whatever I used the last time I tried to do a progress bar, many moons ago.

**Comment by lmaurits** [comment] 2017-10-19 09:54
As I've commented elsewhere, I now suspect that the sluggish performance of BEASTling on large analyses using Glottolog constraints is not related to the initial importing/parsing of GL, but rather inefficient use of that information afterwards.  This means that avoiding unecessary GL imports at all costs for performance reasons is not really a sensible use of time, and so I'm happy to ignore the last check-box in the original post.  This means there's nothing left except making use of CLDF metadata, which means that this issue is now more or less a duplicate of #154.  So I'm closing this issue and further discussion related to the interaction of CLDF and geography can go there.

**Closed as completed by lmaurits** 2017-10-19 09:54 UTC
